info_params:
  path:
    bucket: 'landing_z'
    input: 'input'
    processing: 'processing'
    output: 'output'
  file:
    name: 'despachantes'
  template_search:
    search_path: '/path/airflow/dags/deployments/'
    search_path_global: '/path/airflow/dags/global_modules'
  info_tables:
    project_id: 'Id do projeto na GCP'
    dataset_rz: 'raw_zone'
    table_id: 'despachantes'
