info_params:
  path:
    bucket: 'landing_z'
    input: 'input'
    processing: 'processing'
    output: 'output'
  file:
    name: 'despachantes'
  template_search:
    search_path: '/home/edy/airflow/dags/deployments/'
    search_path_global: '/home/edy/airflow/dags/global_modules'
  info_tables:
    project_id: 'hopeful-canto-394719'
    dataset_rz: 'raw_zone'
    table_id: 'despachantes'